# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password
bindd = SUPER CTRL, K, kanata-restart, exec, sudo /usr/local/bin/restart-kanata.sh



# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, C, Calendar, exec, omarchy-launch-webapp "https://app.hey.com/calendar/weeks/"
bindd = SUPER SHIFT, E, Email, exec, omarchy-launch-webapp "https://app.hey.com"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT CTRL, G, Google Messages, exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bindd = SUPER SHIFT, P, Google Photos, exec, omarchy-launch-or-focus-webapp "Google Photos" "https://photos.google.com/"
bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
bindd = SUPER SHIFT ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

# Swap active window with the one next to it with SUPER + SHIFT + vim motions
bindd = SUPER SHIFT, H, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, L, Swap window to the right, swapwindow, r
bindd = SUPER SHIFT, K, Swap window up, swapwindow, u
bindd = SUPER SHIFT, J, Swap window down, swapwindow, d

# Unbind SUPER J & K from toggle splitscreen, show key bindings, and map SUPER S to toggle splitscreen
unbind = SUPER, J
unbind = SUPER, K
bindd = SUPER, S, Toggle split, togglesplit # dwindle

# Bind move focus keys and move window keys to use vim motions
bindd = SUPER, H, Move focus left, movefocus, l
bindd = SUPER, L, Move focus right, movefocus, r
bindd = SUPER, K, Move focus up, movefocus, u
bindd = SUPER, J, Move focus down, movefocus, d

# Bind move monitor keys
unbind = SUPER SHIFT ALT, UP
unbind = SUPER SHIFT ALT, DOWN
unbind = SUPER SHIFT ALT, LEFT
unbind = SUPER SHIFT ALT, RIGHT

# move active window to monitor above / below / left / right
bindd = SUPER SHIFT ALT, K, Move window to monitor above, movewindow, mon:u
bindd = SUPER SHIFT ALT, J, Move window to monitor down, movewindow, mon:d
bindd = SUPER SHIFT ALT, H, Move window to monitor left, movewindow, mon:l
bindd = SUPER SHIFT ALT, L, Move window to monitor right, movewindow, mon:r

# Totally temporary mouse dpi switch
# faster cursor (e.g. big 4K screen)
bind = SUPER SHIFT, M,  exec, hyprctl -r -- keyword device[logitech-usb-receiver-mouse]:sensitivity 4.0
# slower cursor (e.g. laptop screen)
bind = SUPER SHIFT ALT, M, exec, hyprctl -r -- keyword device[logitech-g703]:sensitivity 0.1

